/^u/.test(typeof define)&&function(r){var y=this.require=function(l){return r[l]};this.define=function(l,C){r[l]=r[l]||C(y)}}({});
define("minified",function(){function r(a){return a}function y(a,b){return(a!=h?""+a:"").replace(b,void 0!=h?void 0:"")}function l(a,b,c){if(a)for(var d=0;d<a.length;d++)b.call(c||a,a[d],d);return a}function C(a,b){var c=[],d=m(b)?b:function(a){return b!=a};l(a,function(b,e){d.call(a,b,e)&&c.push(b)});return c}function K(a,b,c){var d=[];a(b,function(a,e){z(a=c.call(b,a,e))?l(a,function(a){d.push(a)}):a!=h&&d.push(a)});return d}function D(a,b){var c=[];l(a,function(d,f){c.push(b.call(a,d,f))});return c}
function G(a,b){var c=b||{},d;for(d in a)c[d]=a[d]}function H(a,b,c){if(m(a))return a.apply(c&&b,D(c||b,r))}function L(a){D(a,function(a){return H(a,void 0,void 0)})}function m(a){return"function"==typeof a&&!a.item}function z(a){return a&&a.length!=h&&"string"!=typeof a&&!(a&&a.nodeType)&&!m(a)&&a!==E}function M(a,b){for(var c=0;a&&c<a.length;c++)a[c]===b&&a.splice(c--,1)}function F(a){return a.Nia=a.Nia||++R}function I(a,b){var c=[],d={},f;n(a,function(a){n(b(a),function(a){d[f=F(a)]||(c.push(a),
d[f]=!0)})});return c}function S(a,b,c,d,f,e){return function(g,q){var p,t=g||E.event,N=!e,k=q||t.target||t.srcElement;if(e)for(;k&&k!=b&&!(N=e(k));)k=k.parentNode;N&&(p=(!a.apply(v(e?k:b),c||[t,d])||""==f)&&"|"!=f)&&!q&&(t.preventDefault&&(t.preventDefault(),t.stopPropagation()),t.cancelBubble=!0);return!p}}function T(a,b){n(b,function(a){a.element.detachEvent("on"+a.a,a.b)})}function O(a){w?w.push(a):setTimeout(a,0)}function v(a,b,c){return m(a)?O(a):new A(u(a,b,c))}function u(a,b,c){function d(a){a=
K(n,a,function k(a){return z(a)?K(n,a,k):a});return e?C(a,function(a){for(;a=a.parentNode;)if(a==e||c)return a==e}):a}function f(a,b){var c=RegExp("(^|\\s+)"+a+"(?=$|\\s)","i");return function(d){return a?c.test(d[b]):!0}}var e,g,q,p;if(b&&1!=(b=u(b)).length)return I(b,function(b){return u(a,b,c)});e=b&&b[0];if("string"!=typeof a)return d(a);if(e&&1!=(e&&e.nodeType))return[];if(1<(b=a.split(/\s*,\s*/)).length)return I(b,function(a){return u(a,e,c)});if(b=/(\S+)\s+(.+)$/.exec(a))return u(b[2],u(b[1],
e),c);if(a!=(b=y(a,/^#/)))return d(document.getElementById(b));g=(b=/([\w-]*)\.?([\w-]*)/.exec(a))[1];p=b[2];b=(q=document.getElementsByClassName&&p)?(e||document).getElementsByClassName(p):(e||document).getElementsByTagName(g||"*");if(g=q?g:p)b=C(b,f(g,q?"tagName":"className"));return c?d(b):b}function P(a,b){function c(a,b){var c=RegExp("(^|\\s+)"+a+"(?=$|\\s)","i");return function(d){return a?c.test(d[b]):!0}}var d={},f=d;if(m(a))return a;if("number"==typeof a)return function(b,c){return c==a};
if(!a||"*"==a||"string"==typeof a&&(f=/^([\w-]*)\.?([\w-]*)$/.exec(a))){var e=c(f[1],"tagName"),g=c(f[2],"className");return function(a){return 1==(a&&a.nodeType)&&e(a)&&g(a)}}if(b)return function(c){return v(a,b).find(c)!=h};v(a).each(function(a){d[F(a)]=!0});return function(a){return d[F(a)]}}function n(a,b){z(a)?l(a,b):a!=h&&b(a,0);return a}function J(){function a(a,d){b==h&&a!=h&&(b=a,g=z(d)?d:[d],setTimeout(function(){l(c,function(a){a()})},0));return b}var b,c=[],d=arguments,f=d.length,e=0,
g=[];l(d,function p(b,c){try{b.then?b.then(function(b){var d;(b&&"object"==typeof b||m(b))&&m(d=b.then)?p(d,c):(g[c]=D(arguments,r),++e==f&&a(!0,2>f?g[c]:g))},function(b){g[c]=D(arguments,r);a(!1,2>f?g[c]:[g[c][0],g,c])}):b(function(){a(!0,arguments)},function(){a(!1,arguments)})}catch(d){a(!1,[d,g,c])}});a.stop=function(){l(d,function(a){a.stop&&a.stop()});return H(a.stop0)};a.then=function(d,e){function f(){try{var a=b?d:e;m(a)?function U(a){try{var b,c=0;if((a&&"object"==typeof a||m(a))&&m(b=a.then)){if(a===
k)throw new TypeError;b.call(a,function(a){c++||U(a)},function(a){c++||k(!1,[a])});k.stop0=a.stop}else k(!0,[a])}catch(d){c++||k(!1,[d])}}(H(a,V,g)):k(b,g)}catch(c){k(!1,[c])}}var k=J();k.stop0=a.stop;b!=h?setTimeout(f,0):c.push(f);return k};return a}function A(a,b){var c=0;if(a)for(var d=0,f=a.length;d<f;d++){var e=a[d];if(b&&z(e))for(var g=0,q=e.length;g<q;g++)this[c++]=e[g];else this[c++]=e}else this[c++]=b;this.length=c;this._=!0}var E=this,R=1,B={},w=/^[ic]/.test(document.readyState)?h:[],x=
!!document.all&&!document.addEventListener,h=null,V;G({each:function(a){return function(b,c,d){return a(this,b,c,d)}}(l),f:0,trav:function(a,b,c){var d="number"==typeof b,f=P(d?h:b),e=d?b:c;return new A(I(this,function(b){for(var c=[];(b=b[a])&&c.length!=e;)f(b)&&c.push(b);return c}))},up:function(a,b){return this.trav("parentNode",a,b||1)},on:function(a,b,c,d,f){return m(b)?this.on(h,a,b,c,f):"string"==typeof d?this.on(a,b,c,h,d):this.each(function(e,g){n(a?u(a,e):e,function(a){n((b!=h?""+b:"").split(/\s/),
function(b){var e=y(b,/[?|]/),h=!!f&&("blur"==e||"focus"==e),k=S(c,a,d,g,y(b,/[^?|]/g),f&&P(f,a));b={element:a,b:k,a:e,c:h};(c.M=c.M||[]).push(b);x?(a.attachEvent("on"+b.a+(h?"in":""),k),e=F(a),(B[e]=B[e]||[]).push(b)):(a.addEventListener(e,k,h),(a.M=a.M||[]).push(b))})})})},onOver:function(a,b){var c=this,d=[];return m(b)?this.on(a,"|mouseover |mouseout",function(a,e){var g=a.relatedTarget||a.toElement,h="mouseout"!=a.type;d[e]===h||!h&&g&&(g==c[e]||v(g).up(c[e]).length)||(d[e]=h,b.call(this,h,a))}):
this.onOver(h,a)},onFocus:function(a,b,c){return m(b)?this.on(a,"|blur",b,[!1],c).on(a,"|focus",b,[!0],c):this.onFocus(h,a,b)},onChange:function(a,b,c){return m(b)?this.on(a,x?"|propertychange |change |keyup |clicked":"|input |change |clicked",function(a,c){var e=this[0],g;g=x&&/select/i.test(e.tagName)?e.options[e.selectedIndex].text:/ox|io/i.test(e.type)?e.checked:e.value;g!=e.NiaP&&b.call(this,e.NiaP=g,c)},c):this.onChange(h,a,b)},onClick:function(a,b,c,d){return m(b)?this.on(a,"click",b,c,d):
this.onClick(h,a,b,c)},trigger:function(a,b){return this.each(function(c){for(var d,f=c;f&&!d;)n(x?B[f.Nia]:f.M,function(e){e.a==a&&(d=d||!e.b(b,c))}),f=f.parentNode})},e:0},A.prototype);G({ready:O,off:function(a){n(a.M,function(a){x?(a.element.detachEvent("on"+a.a+(a.c?"in":""),a.b),M(B[a.element.Nia],a)):(a.element.removeEventListener(a.a,a.b,a.c),M(a.element.M,a))});a.M=h},wait:function(a,b){var c=J(),d=setTimeout(function(){c(!0,b)},a);c.stop0=function(){c(!1);clearTimeout(d)};return c}},v);G({each:l,
toObject:function(a,b){var c={};l(a,function(a){c[a]=b});return c},d:0,promise:J},function(){return new A(arguments,!0)});if(x){var Q=function(){L(w);w=h};document.attachEvent("onreadystatechange",function(){/^[ic]/.test(document.readyState)&&Q()});E.attachEvent("onload",Q)}else document.addEventListener("DOMContentLoaded",function(){L(w);w=h},!1);E.g=function(){n(B,T)};return{$:v,M:A,getter:{},setter:{}}});
